// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
  id: string;
  createdAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Business = {
  Nome: string;
  Resumo: string;
  Score: number;
  Site: string;
  EBITDA: number;
  'Data do EBITDA': string;
};

export type Ranking = {
  id: string;
  url: string;
  ebitda: number;
  businesses: Business[];
  dealSize: number;
  createdAt: number;
  tags: string[];
};
